version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "loonghao"
    assignees:
      - "loonghao"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "loonghao"
    assignees:
      - "loonghao"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "loonghao"
    assignees:
      - "loonghao"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
