[package]
name = "rez-core"
version = "0.1.0"
edition = "2021"
authors = ["Rez Core Team <rez-core@example.com>"]
description = "High-performance core components for Rez package manager"
license = "Apache-2.0"
repository = "https://github.com/loonghao/rez-core"
keywords = ["rez", "package-manager", "dependency-resolution", "version-management"]
categories = ["development-tools"]

[lib]
name = "rez_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
# pyo3 = { version = "0.20", features = ["extension-module"] }  # Temporarily disabled
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7"
lru = "0.12"
tokio = { version = "1.0", features = ["full"] }
regex = "1.10"
thiserror = "1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"

[[bench]]
name = "version_benchmark"
harness = false

# [build-dependencies]  # Temporarily disabled
# pyo3-build-config = "0.20"
