[workspace]
members = [
    "crates/rez-core-common",
    "crates/rez-core-version",
    "crates/rez-core-package",
    "crates/rez-core-solver",
    "crates/rez-core-repository",
    "crates/rez-core-context",
    "crates/rez-core-build",
    "crates/rez-core-cache",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["LongHao <hal.long@outlook.com>"]
license = "Apache-2.0"
repository = "https://github.com/loonghao/rez-core"
keywords = ["rez", "package-manager", "dependency-resolution", "version-management"]
categories = ["development-tools"]

[workspace.dependencies]
# External dependencies
pyo3 = { version = "0.25", features = ["extension-module", "abi3-py38"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
rayon = "1.7"
lru = "0.14.0"
tokio = { version = "1.0", features = ["full"] }
regex = "1.10"
thiserror = "2.0"
rand = "0.8"
clap = { version = "4.0", features = ["derive", "env"] }

# Dev dependencies
criterion = { version = "0.6", features = ["html_reports"] }
proptest = "1.0"
rstest = "0.25"
tempfile = "3.0"
assert_matches = "1.5"
pretty_assertions = "1.4"
serial_test = "3.0"

[package]
name = "rez-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "High-performance core components for Rez package manager (meta-package)"
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "rez_core"
crate-type = ["rlib"]

[features]
default = []
python-bindings = [
    "rez-core-common/python-bindings",
    "rez-core-version/python-bindings",
    "rez-core-package/python-bindings",
    "rez-core-context/python-bindings",
    "rez-core-solver/python-bindings",
    "pyo3"
]

[[bin]]
name = "rez"
path = "src/bin/rez.rs"

[dependencies]
# Workspace crates
rez-core-common = { path = "crates/rez-core-common", default-features = false }
rez-core-version = { path = "crates/rez-core-version", default-features = false }
rez-core-package = { path = "crates/rez-core-package", default-features = false }
rez-core-solver = { path = "crates/rez-core-solver", default-features = false }
rez-core-repository = { path = "crates/rez-core-repository", default-features = false }
rez-core-context = { path = "crates/rez-core-context", default-features = false }
# rez-core-rex = { path = "crates/rez-core-rex" }  # Temporarily disabled due to compilation errors
rez-core-build = { path = "crates/rez-core-build" }
rez-core-cache = { path = "crates/rez-core-cache" }
# rez-core-python = { path = "crates/rez-core-python" }  # Temporarily disabled due to DLL issues

# Python bindings - conditionally enabled
pyo3 = { workspace = true, optional = true }

# CLI dependencies
clap.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
regex.workspace = true
tempfile.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
rstest.workspace = true
tempfile.workspace = true
assert_matches.workspace = true
pretty_assertions.workspace = true
serial_test.workspace = true
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true



[[bench]]
name = "version_benchmark"
harness = false

[[bench]]
name = "comprehensive_benchmark_suite"
harness = false

[[bench]]
name = "package_benchmark"
harness = false

[[bench]]
name = "simple_package_benchmark"
harness = false

# Removed redundant benchmarks

[[bench]]
name = "solver_benchmark"
harness = false

[[bench]]
name = "solver_benchmark_main"
harness = false

# Simplified solver benchmarks

[[bench]]
name = "context_benchmark"
harness = false

[[bench]]
name = "context_benchmark_main"
harness = false

[[bench]]
name = "simple_context_benchmark"
harness = false

# Rex System Benchmarks - Temporarily disabled
# [[bench]]
# name = "rex_benchmark_main"
# harness = false

# [[bench]]
# name = "simple_rex_benchmark"
# harness = false

# Build and Cache System Benchmarks
[[bench]]
name = "build_cache_benchmark_main"
harness = false

[[bench]]
name = "simple_build_cache_benchmark"
harness = false

# Performance Validation Benchmarks
[[bench]]
name = "performance_validation_benchmark"
harness = false

[[bench]]
name = "performance_validation_main"
harness = false

# [build-dependencies]
# pyo3-build-config = "0.25"  # Only needed for Python bindings

# flamegraph = ["pprof"]

# Linting configuration
[lints.rust]
# Allow unused imports for Python bindings that may not be used in all builds
unused_imports = "allow"
# Allow dead code for experimental features
dead_code = "allow"

[lints.clippy]
# Allow some clippy lints that are too strict for development
too_many_arguments = "allow"
module_inception = "allow"
# Focus on critical issues only
complexity = { level = "warn", priority = -1 }
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
perf = { level = "warn", priority = -1 }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
lto = false
