[package]
name = "rez-core"
version = "0.1.0"
edition = "2021"
authors = ["LongHao <hal.long@outlook.com>"]
description = "High-performance core components for Rez package manager"
license = "Apache-2.0"
repository = "https://github.com/loonghao/rez-core"
keywords = ["rez", "package-manager", "dependency-resolution", "version-management"]
categories = ["development-tools"]

[lib]
name = "rez_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module", "abi3-py38"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7"
lru = "0.14.0"
tokio = { version = "1.0", features = ["full"] }
regex = "1.10"
thiserror = "2.0"

# Performance profiling (optional)
pprof = { version = "0.14", features = ["flamegraph", "criterion"], optional = true }

[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }
proptest = "1.0"
rstest = "0.25"
tempfile = "3.0"
assert_matches = "1.5"
pretty_assertions = "1.4"
serial_test = "3.0"



[[bench]]
name = "version_benchmark"
harness = false

[build-dependencies]
pyo3-build-config = "0.25"

[features]
default = []
flamegraph = ["pprof"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
lto = false
