[package]
name = "rez-next-solver-standalone"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_astar_standalone"
path = "src/bin/test_astar_standalone.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
dashmap = "6.0"
smallvec = "1.11"
futures = "0.3"
