[package]
name = "rez-next-solver"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Intelligent dependency resolution with A* heuristic algorithms and 3-5x performance improvement"
license.workspace = true
repository.workspace = true
homepage = "https://github.com/loonghao/rez-core"
documentation = "https://docs.rs/rez-next-solver"
readme = "README.md"
keywords = ["solver", "dependency", "resolution", "algorithm", "rez"]
categories = ["development-tools", "algorithms", "data-structures"]
exclude = ["benches/", "examples/"]

[features]
default = []
# Temporarily disabled Python bindings
# python-bindings = ["pyo3", "rez-next-common/python-bindings", "rez-next-package/python-bindings", "rez-next-version/python-bindings"]

[dependencies]
rez-next-common = { path = "../rez-next-common" }
rez-next-version = { path = "../rez-next-version" }
rez-next-package = { path = "../rez-next-package" }
rez-next-repository = { path = "../rez-next-repository" }
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
thiserror.workspace = true
# Temporarily disabled Python bindings
# pyo3 = { workspace = true, optional = true }
tokio.workspace = true
regex = "1.11"
dashmap = "6.1"
smallvec = "1.15"
futures = "0.3"

# Bins temporarily disabled - astar feature not implemented yet
# [[bin]]
# name = "test_astar"
# path = "src/bin/test_astar.rs"

# [[bin]]
# name = "test_heuristics"
# path = "src/bin/test_heuristics.rs"

# [[bin]]
# name = "heuristic_demo"
# path = "src/bin/heuristic_demo.rs"

[dev-dependencies]
rstest.workspace = true
proptest.workspace = true
tempfile.workspace = true
pretty_assertions.workspace = true
assert_matches.workspace = true
