[package]
name = "rez-lsp-integration-test"
version = "0.1.0"
edition = "2021"
description = "Integration test for rez-lsp-server using rez-core crates"

[dependencies]
# Core rez-core crates that rez-lsp-server would use
rez-core-version = { path = "../../crates/rez-core-version" }

# Additional dependencies for testing
serde_json = "1.0"
