name: Rust Audit

on:
  push:
    branches: ["main", "ci-setup"]
    paths:
      - Cargo.lock
      - Cargo.toml
  pull_request:
    paths:
      - Cargo.lock
      - Cargo.toml
  schedule:
    - cron: '17 0 * * 0'

permissions:
  contents: read

env:
  # Improve network reliability for cargo operations
  CARGO_NET_RETRY: "10"
  CARGO_NET_TIMEOUT: "300"
  # Reduce API rate limiting issues
  CARGO_HTTP_TIMEOUT: "300"
  CARGO_HTTP_LOW_SPEED_LIMIT: "10"
  CARGO_HTTP_LOW_SPEED_TIMEOUT: "30"

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent hanging
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: dtolnay/rust-toolchain@d0592fe69e35bc8f12e3dbaf9ad2694d976cb8e3 # stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          shared-key: rust-audit
          cache-on-failure: true

      - name: Install cargo-audit with retry
        uses: ./.github/actions/retry-action
        with:
          command: |
            echo "Installing cargo-audit..."
            cargo install cargo-audit --locked
          max_attempts: 3
          timeout_minutes: 15
          retry_wait_seconds: 60

      - name: Update advisory database with retry
        uses: ./.github/actions/retry-action
        with:
          command: |
            echo "Updating advisory database..."
            cargo audit --update-db
          max_attempts: 5
          timeout_minutes: 10
          retry_wait_seconds: 120
          continue_on_error: false

      - name: Run cargo audit with retry
        uses: ./.github/actions/retry-action
        with:
          command: |
            echo "Running cargo audit..."
            cargo audit --timeout 300 --format json --output-format json > audit-results.json || true
            cargo audit --timeout 300
          max_attempts: 5
          timeout_minutes: 15
          retry_wait_seconds: 120
          continue_on_error: false

      - name: Upload audit results
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always()
        with:
          name: cargo-audit-results
          path: audit-results.json
          retention-days: 30

      - name: Run cargo deny with retry
        uses: ./.github/actions/retry-action
        with:
          command: |
            echo "Running cargo deny check..."
            cargo deny --timeout 300 check --hide-inclusion-graph
          max_attempts: 5
          timeout_minutes: 15
          retry_wait_seconds: 120
          continue_on_error: false

      - name: Run cargo deny (fallback)
        uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2.0.11
        if: failure()
        continue-on-error: true
