name: Python Test Suite

on:
  push:
    branches: ["main", "ci-setup"]
    paths:
      - .github/workflows/*_python.yml
      - python/**
      - src/**
      - Cargo.lock
      - Cargo.toml
      - pyproject.toml
      - tests/python/**
  pull_request:
    paths:
      - .github/workflows/*_python.yml
      - python/**
      - src/**
      - Cargo.lock
      - Cargo.toml
      - pyproject.toml
      - tests/python/**

permissions:
  contents: read

jobs:
  test:
    name: Python test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - version: "3.8"
            freethreaded: false
          - version: "3.9"
            freethreaded: false
          - version: "3.10"
            freethreaded: false
          - version: "3.11"
            freethreaded: false
          - version: "3.12"
            freethreaded: false
          - version: "3.13"
            freethreaded: false
          - version: "3.13"
            freethreaded: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: dtolnay/rust-toolchain@d0592fe69e35bc8f12e3dbaf9ad2694d976cb8e3 # stable

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          shared-key: lang-python-${{ runner.os }}

      - name: Run Cargo Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Cargo Fmt
        run: cargo fmt --check

      - name: Setup Python ${{ matrix.python-version.version }} freethreaded=${{ matrix.python-version.freethreaded }}
        id: setup-python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: ${{ matrix.python-version.version }}
          freethreaded: ${{ matrix.python-version.freethreaded }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies and run Python tests (Unix)
        if: runner.os != 'Windows'
        run: |
          make install
          make lint-python
          make test-python
          make testcov

      - name: Install dependencies and run Python tests (Windows)
        if: runner.os == 'Windows'
        run: |
          uv sync --all-extras
          uv pip install -e .
          .\scripts\build.ps1 build-dev
          .\scripts\build.ps1 lint-python
          .\scripts\build.ps1 test-python

      - uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          files: coverage.xml
          flags: lang-python
